"""Extract manufacturer illustrations from printed p.7; installed set unconfirmed."""
from pathlib import Path
from io import BytesIO
import base64, hashlib, json
from PIL import Image, ImageDraw
from pypdf import PdfReader
ROOT=Path(__file__).resolve().parent
SOURCE=ROOT/'375z-manual.pdf'
page=PdfReader(SOURCE).pages[8]
source=next(item.image.convert('RGB') for item in page.images if item.image.width>2000)
green=source.crop((0,0,source.width,280)).getchannel('G');pixels=green.load()
occupied=[sum(pixels[x,y]<128 for y in range(280))>5 for x in range(green.width)]
ranges=[];start=None
for x,yes in enumerate(occupied+[False]):
 if yes and start is None:start=x
 elif not yes and start is not None:
  if x-start>100:ranges.append((start,x))
  start=None
assert len(ranges)==7,ranges
encoded=[];masks=[];boxes=[];gobo1_thumbnail=None
for x0,x1 in ranges:
 ys=[y for y in range(280) if any(pixels[x,y]<128 for x in range(x0,x1))]
 box=(x0,min(ys),x1,max(ys)+1);crop=green.crop(box)
 # Green isolates white apertures even on gobo1's magenta illustration.
 mask=crop.point(lambda v:max(0,min(255,round((v-64)*255/160))))
 aperture=Image.new('L',crop.size);ImageDraw.Draw(aperture).ellipse((1,1,crop.width-2,crop.height-2),fill=255)
 if not encoded:
  rgb=Image.new('RGB',crop.size);rgb.paste(source.crop(box),(0,0),aperture);png=BytesIO();rgb.resize((512,512),Image.Resampling.LANCZOS).save(png,format='PNG',optimize=True)
  gobo1_thumbnail='data:image/png;base64,'+base64.b64encode(png.getvalue()).decode()
 final=Image.new('L',crop.size);final.paste(mask,(0,0),aperture);final=final.resize((512,512),Image.Resampling.LANCZOS)
 png=BytesIO();final.save(png,format='PNG',optimize=True)
 encoded.append('data:image/png;base64,'+base64.b64encode(png.getvalue()).decode());masks.append(final);boxes.append(box)
metadata={'manual':'Intimidator Spot 375Z IRC User Manual Rev.6','printedPage':7,'pdfPageIndex':8,
 'sha256':hashlib.sha256(SOURCE.read_bytes()).hexdigest(),'sourceImageSize':source.size,'cropBoxes':boxes,
 'url':'https://fr.chauvetdj.com/wp-content/uploads/2017/07/Intimidator_Spot_375Z_IRC_UM_Rev6.pdf',
 'limitation':'Motifs fabricant extraits. Jeu installé non confirmé. Teinte magenta du gobo1 illustrée mais transmission spectrale non calibrée : masque des ouvertures blanches uniquement.'}
(ROOT/'manufacturer-gobo-masks.js').write_text('// Generated by extract-manufacturer-gobos.py; original source shapes, not redrawings.\nexport const goboSource='+json.dumps(metadata,ensure_ascii=False)+';\nexport const manufacturerGoboMasks='+json.dumps(encoded)+';\nexport const gobo1Illustration='+json.dumps(gobo1_thumbnail)+';\n',encoding='utf-8')
proof=Image.new('RGB',(1344,192),'#1a1a1a')
for index,mask in enumerate(masks):proof.paste(mask.resize((192,192),Image.Resampling.LANCZOS),(index*192,0))
proof_path=ROOT.parent.parent/'tmp'/'pdfs'/'grand-remix'/'gobo-masks-manufacturer.png';proof_path.parent.mkdir(parents=True,exist_ok=True);proof.save(proof_path)
print('Seven original masks extracted:',boxes)
