from pathlib import Path
p=Path('ambiences.js');s=p.read_text(encoding='utf-8').replace("name:'Slam · lumière claire'","name:'Slam · pulsation blanche'").replace("description:'Visage blanc doux · musique et image en avant'","description:'Visage blanc · gobos et couleurs en mouvement'").replace("name:'Slam · chaleureux'","name:'Slam · ambre et rythme'")
s=s.replace("case 'slam_white':dj(32);face(68);on('203 204',25,'#35dcff');break;","case 'slam_white':dj(32);face(68);on('203 204',25,'#35dcff');room(38,16,5);break;")
s=s.replace("{gobo:7,rotation:3,movement:'static',zoom:20}","{gobo:7,rotation:6,movement:'sweep',amplitude:6,period:14,zoom:20}")
p.write_text(s,encoding='utf-8')
p=Path('scene.js');s=p.read_text(encoding='utf-8').replace('ambienceDefinitions,createAmbience','ambienceDefinitions,createAmbience,ambienceDuration,ambienceEnvelope')
s=s.replace("ambience:null,view:","ambience:null,ambienceCustomized:false,ambiencePlaying:false,view:")
s=s.replace("const active=$('#fixtures-visible').checked&&!f.previewBlocked&&fx.dimmer>0;", "const cueLevel=ambienceEnvelope(state.ambience,f.id,time);const active=$('#fixtures-visible').checked&&!f.previewBlocked&&fx.dimmer>0&&cueLevel>.001;")
s=s.replace('state.level*fx.dimmer/100*fogPreview.density','state.level*fx.dimmer/100*cueLevel*fogPreview.density').replace('optics.power*fx.dimmer/100*state.level:0','optics.power*fx.dimmer/100*state.level*cueLevel:0')
s=s.replace("'Réglage libre · blanc à 100 % au départ';","'Réglage libre · blanc à 100 % au départ';$('#ambience-restart').disabled=!state.ambience;$('#ambience-play').textContent=state.ambiencePlaying?'Arrêter le défilement':'Lire les ambiances';")
a=s.index("const ambienceButtons=$('#ambience-buttons');");b=s.index("\n$('#light-level')",a)
s=s[:a]+'''function activateAmbience(id){const p=ambienceDefinitions.find(p=>p.id===id);if(!p)return;state.ambience=p.id;state.ambienceCustomized=false;state.mode=p.mode;state.roomDark=true;state.videoOn=p.videoOn;state.level=1;state.motion=true;state.beams=true;$('#light-level').value=100;$('#level-value').textContent='100 %';$('#motion').checked=true;$('#beams').checked=true;$('#fixtures-visible').checked=true;fixtureLayer.visible=true;elapsed=0;fogPreview.reset();syncFog();lightingEditor.applyPreset(createAmbience(p.id,fixtures));}
const ambienceButtons=$('#ambience-buttons');for(const p of ambienceDefinitions){const b=document.createElement('button');b.dataset.ambience=p.id;b.setAttribute('aria-pressed','false');b.textContent=p.name;b.title=p.description;b.onclick=()=>{state.ambiencePlaying=false;activateAmbience(p.id);};ambienceButtons.appendChild(b);}
$('#ambience-restart').onclick=()=>{if(state.ambience){elapsed=0;state.motion=true;$('#motion').checked=true;}};
$('#ambience-play').onclick=()=>{state.ambiencePlaying=!state.ambiencePlaying;if(state.ambiencePlaying)activateAmbience(ambienceDefinitions[0].id);else applyMode();};
'''+s[b:]
s=s.replace("if(state.motion)elapsed+=dt;","if(state.motion)elapsed+=dt;if(state.ambiencePlaying&&elapsed>=ambienceDuration){const next=(ambienceDefinitions.findIndex(p=>p.id===state.ambience)+1)%ambienceDefinitions.length;activateAmbience(ambienceDefinitions[next].id);}if(state.ambience)$('#ambience-time').textContent=(state.motion?'Cycle de 25 s':'En pause')+' · '+String(Math.floor(elapsed%25)).padStart(2,'0')+' / 25 s'+(state.ambienceCustomized?' · ajustée':'');else $('#ambience-time').textContent='';")
s=s.replace('onEdit:()=>{state.ambience=null;},roomPreset:dark=>{state.ambience=null;','onEdit:()=>{state.ambienceCustomized=!!state.ambience;},roomPreset:dark=>{state.ambience=null;state.ambiencePlaying=false;state.ambienceCustomized=false;')
s=s.replace('capture:()=>({ambience:state.ambience,motion:', 'capture:()=>({ambience:state.ambience,ambienceCustomized:state.ambienceCustomized,motion:')
s=s.replace('restore:v=>{transition=null;state.ambience=', 'restore:v=>{transition=null;elapsed=0;state.ambiencePlaying=false;state.ambienceCustomized=!!v.ambienceCustomized;state.ambience=')
p.write_text(s,encoding='utf-8')
p=Path('index.template.html');s=p.read_text(encoding='utf-8').replace('<p id="ambience-status"', '<div class="studio-actions"><button id="ambience-restart" disabled>Rejouer les 25 s</button><button id="ambience-play">Lire les ambiances</button></div><p id="ambience-time" class="note"></p><p id="ambience-status"');p.write_text(s,encoding='utf-8')
