from pathlib import Path
p=Path('build-studio-appendix.py');s=p.read_text(encoding='utf-8');s=s.replace("head(8,'SCÈNES ENREGISTRÉES - BROUILLARD - MODE D’EMPLOI')","head(8,'AMBIANCES DE 25 S - BROUILLARD - MODE D’EMPLOI')")
a=s.index('for title,body in [');b=s.index(']:\n text(left,y,title',a)
s=s[:a]+'''for title,body in [
('1. Démarrer et choisir','Vue de face. Lumières utilisables blanches à 100 %, brouillard OFF. Les appareils rouges restent inutilisés. Les ambiances sont en haut à droite. « Réinitialiser » restaure ce départ. « Noir spectacle » coupe spots et vidéo, en conservant le bar. La vidéo possède aussi sa propre commande ; éteinte, ses pointillés disparaissent.'),
('2. Neuf ambiances de 25 secondes','Entrée du public : scène noire, salle blanche. Ouverture : DJ magenta, face artiste blanche, salle éteinte. Premier artiste : artiste rouge, gobos cyan mobiles, salle cyan/magenta/vert. Pulsation blanche, Nuit bleue et Ambre et rythme : variantes pour les morceaux. Transition DJ, Danse tricolore et Finale hip-hop : mouvements plus présents. Chaque cycle alterne ouvertures et fermetures progressives dans la salle, avec une face stable. « Rejouer » relance ; « Lire les ambiances » les enchaîne. Projection active hors accueil. Bar permanent ; brouillard OFF.'),
('3. Composer et enregistrer','Cliquer sur un spot déplie ses réglages et son contour vert. Couleurs et gobos se choisissent visuellement. Quatre mouvements de lyre : balayage, vertical, ellipse, huit ; plus Fixe. La rotation du gobo est indépendante. Les fixes ne deviennent pas motorisés. Donner un nom à l’ambiance : elle rejoint la liste du haut. Les scènes personnelles sont locales au navigateur ; exporter le JSON pour les conserver ou les transmettre.'),
('4. Slam, musique et projection','Neuf artistes, deux slams chacun, puis une finale hip-hop : utiliser les ambiances selon les musiques et le rythme des performances. Les cycles sont des propositions visuelles, sans analyse audio ni synchronisation au tempo des morceaux. Les lyres offrent du cyan, pas de bleu profond. PAR et découpes restent blancs sans gélatines confirmées. Les orientations des fixes sont conservées.'),
('5. Navigation et portée','Souris : glisser pour tourner, molette pour avancer/reculer, clic droit pour déplacer. W/A/S/D ou flèches disponibles. Gobos redessinés d’après le manuel ; intensités relatives sans calibration lux. Brouillard, réflexion, couleurs et matériaux restent approximatifs. Aucun contrôle réel de console ou d’appareil. Ces ambiances ne remplacent pas le focus et la programmation du DT.')
''' + s[b:]
s=s.replace('Fidélité du modèle','Fidélité du modèle')
p.write_text(s,encoding='utf-8')
